// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xstjfkcmivnazspvrkhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzdGpma2NtaXZuYXpzcHZya2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjUwNDc4ODMsImV4cCI6MjA0MDYyMzg4M30.u5JoZQ7EjmCrOvEfAjZT-WD-5EBHDx87wGMlw3MXQE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);